OnlineStoreMVC/OnlineStoreMVC/Controllers/GoodController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OnlineStoreMVC.Models;

namespace OnlineStoreMVC.Controllers
{
    public class GoodController : ApplicationBaseController
    {
        private ActionReport AddGood(GoodRegisterViewModels model)
        {
            using (OnlineStoreEntities context = new OnlineStoreEntities())
            {
                ActionReport report = new ActionReport();
                try
                {
                    if (context.Goods.Any(x => x.Name == model.Name))
                    {
                        report.HasError = true;
                        report.Message = "نام کالا تکراری است";
                        return report;
                    }
                    Good good = new Good();
                    good.Name = model.Name;
                    good.IdGroup = model.IdGroup;
                    good.Description = model.Description;
                    good.Author = model.Author;
                    good.Translator = model.Translator;
                    good.Price = model.Price;
                    good.Publisher = model.Publisher;
                    good.Edition = model.Edition;
                    good.Code = model.Code;
                    context.Goods.Add(good);
                    context.SaveChanges();
                    return report;
                }
                catch (Exception ex)
                {
                    report.HasError = true;
                    report.Message = ex.Message;
                    return report;
                }
            }
        }

        private ActionReport EditGood(GoodEditViewModels model)
        {
            using (OnlineStoreEntities context = new OnlineStoreEntities())
            {
                ActionReport report = new ActionReport();
                try
                {
                    Good good = context.Goods.Find(model.Id);
                    good.Name = model.Name;
                    good.Description = model.Description;
                    good.Author = model.Author;
                    good.Code = model.Code;
                    good.Price = model.Price;
                    good.Publisher = model.Publisher;
                    good.Translator = model.Translator;
                    good.IdGroup = model.IdGroup;
                    context.Entry(good).State = EntityState.Modified;
                    context.SaveChanges();
                    return report;
                }
                catch (Exception ex)
                {
                    report.HasError = true;
                    report.Message = ex.Message;
                    return report;
                }
            }
        }
        private List<Good> GetGoodList(long? idgrp, string searchstring)
        {
            using (OnlineStoreEntities context = new OnlineStoreEntities())
            {
                bool checkfilter = string.IsNullOrWhiteSpace(searchstring);
                return context.Goods.Where(x => (!idgrp.HasValue || x.IdGroup == idgrp) && (checkfilter || x.Name.Contains(searchstring))).ToList();
            }
        }

        private Good GetGoodById(long id)
        {
            using (OnlineStoreEntities context = new OnlineStoreEntities())
            {
                return context.Goods.Find(id);
            }
        }
        private ActionReport DeleteGoodById(long id)
        {
            using (OnlineStoreEntities context = new OnlineStoreEntities())
            {
                ActionReport report = new ActionReport();
                try
                {
                    Good good = context.Goods.Find(id);
                    context.Goods.Remove(good);
                    context.SaveChanges();
                    return report;
                }
                catch (Exception ex)
                {
                    report.HasError = true;
                    report.Message = ex.Message;
                    return report;
                }
            }
        }

        private List<Group> GetGroupsList()
        {
            using (OnlineStoreEntities context = new OnlineStoreEntities())
            {
                return context.Groups.ToList();
            }
        }

        // GET: /Good/
        public ActionResult Index(long? idgrp, string searchstring)
        {
            return View(GetGoodList(idgrp, searchstring).Select(x => new GoodViewModel(x)));
        }

        // GET: /Good/
        public ActionResult _PartialIndex(long? idgrp)
        {
            return PartialView(GetGoodList(idgrp, null).Select(x => new GoodViewModel(x)));
        }

        // GET: /Good/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Good good = GetGoodById(id.Value);
            if (good == null)
            {
                return HttpNotFound();
            }
            return View(new GoodViewModel(good));
        }

        // GET: /Good/Create
        [HttpGet]
        [Authorize(Roles="admin")]
        public ActionResult Create()
        {
            ViewBag.Groups = new SelectList(GetGroupsList().Where(x=> x.Level == 3), "Id", "Description");
            return View();
        }

        // POST: /Good/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public ActionResult Create(GoodRegisterViewModels model)
        {
            if (ModelState.IsValid)
            {
                var report = AddGood(model);
                if (!report.HasError)
                    return RedirectToAction("Index");
                else
                    ModelState.AddModelError("", report.Message);
            }
            return View(model);
        }

        // GET: /Good/Edit/5
        [HttpGet]
        [Authorize(Roles = "admin")]
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Good good = GetGoodById(id.Value);
            if (good == null)
            {
                return HttpNotFound();
            }
            ViewBag.Groups = new SelectList(GetGroupsList().Where(x => x.Level == 3), "Id", "Description", good.IdGroup);
            return View(new GoodEditViewModels(good));
        }

        // POST: /Good/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public ActionResult Edit(GoodEditViewModels model)
        {
            if (ModelState.IsValid)
            {
                var report = EditGood(model);
                if (!report.HasError)
                    return RedirectToAction("Index");
                else
                    ModelState.AddModelError("", report.Message);
            }
            return View(model);
        }

        [Authorize(Roles = "admin")]
        // GET: /Good/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Good good = GetGoodById(id.Value);
            if (good == null)
            {
                return HttpNotFound();
            }
            return View(new GoodViewModel(good));
        }

        // POST: /Good/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public ActionResult DeleteConfirmed(long id)
        {
            var report = DeleteGoodById(id);
            return RedirectToAction("Index");
        }
    }
}

OnlineStoreMVC/OnlineStoreMVC/Controllers/InvoiceController.cs
using OnlineStoreMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineStoreMVC.Controllers
{
    public class InvoiceController : ApplicationBaseController
    {
        private User GetUserByUsername(string username)
        {
            using (OnlineStoreEntities contex = new OnlineStoreEntities())
            {
                return contex.Users.SingleOrDefault(x => x.Username == username);
            }
        }
        private ActionReport AddGoodToInvoice(long idgood, long iduser)
        {
            using(var context = new OnlineStoreEntities())
            {
                ActionReport report = new ActionReport();
                try
                {
                    Invoice invoice = new Invoice();
                    invoice.IdGood = idgood;
                    invoice.IdUser = iduser;
                    invoice.IdInvoiceState = 1;
                    context.Invoices.Add(invoice);
                    context.SaveChanges();
                    return report;
                }
                catch (Exception ex)
                {
                    report.HasError = true;
                    report.Message = ex.Message;
                    return report;
                }
            }
        }
        private List<vw_Invoice> GetCurrentUserInvoices()
        {
            using(var context = new OnlineStoreEntities())
            {
                var user = context.Users.SingleOrDefault(x=> x.Username == User.Identity.Name);
                return context.vw_Invoice.Where(x => x.IdUser == user.Id).ToList();
            }
        }
        private List<vw_Invoice> GetAllUsersPaidInvoices()
        {
            using(var context = new OnlineStoreEntities())
            {
                return context.vw_Invoice.Where(x => x.IdInvoiceState == 2).ToList();
            }
        }
        private int GetCurrentUserCartCount()
        {
            using (var context = new OnlineStoreEntities())
            {
                var user = context.Users.SingleOrDefault(x => x.Username == User.Identity.Name);
                return context.vw_Invoice.Count(x => x.IdUser == user.Id && x.IdInvoiceState == 1);
            }
        }


        private ActionReport PurchaseGoods()
        {
            using (var context = new OnlineStoreEntities())
            {
                ActionReport report = new ActionReport();
                try
                {
                    var user = context.Users.SingleOrDefault(x => x.Username == User.Identity.Name);
                    var ivcs = context.Invoices.Where(x => x.IdUser == user.Id && x.IdInvoiceState == 1);
                    foreach (var ivc in ivcs)
                    {
                        ivc.IdInvoiceState = 2;
                        var good = context.Goods.Find(ivc.IdGood);
                        if (good != null)
                            ivc.PaidPrice = good.Price;
                        context.Entry(ivc).State = System.Data.Entity.EntityState.Modified;
                    }
                    context.SaveChanges(); 
                    return report;
                }
                catch (Exception ex)
                {
                    report.HasError = true;
                    report.Message = ex.Message;
                    return report;
                }
            }
        }
        private ActionReport DeleteInvoiceById(long id, long userid)
        {
            using(var context = new OnlineStoreEntities())
            {
                ActionReport report = new ActionReport();
                try
                {
                    var invoice = context.Invoices.SingleOrDefault(x => x.IdUser == userid && x.Id == id);
                    if (invoice != null)
                    {
                        context.Invoices.Remove(invoice);
                        context.SaveChanges();
                    }
                    else
                    {
                        report.HasError = true;
                        report.Message = "شما به این فاکتور دسترسی ندارید";
                        return report;
                    }
                    return report;
                }
                catch(Exception ex)
                {
                    report.HasError = true;
                    report.Message = ex.Message;
                    return report;
                }
            }
        }
        //
        // GET: /Invoice/
        [Authorize]
        public ActionResult _PartialInvoiceList()
        {
            var items = GetCurrentUserInvoices().Where(x=> x.IdInvoiceState == 1).Select(x => new InvoiceModel(x)).ToList();
            return PartialView(items);
        }
        //
        // GET: /Invoice/
        [HttpGet]
        [Authorize(Roles="admin")]
        public ActionResult _LastPaidInvoices()
        {
            var items = GetAllUsersPaidInvoices().Select(x => new InvoiceModel(x)).ToList();
            return PartialView(items);
        }
        //
        // GET: /Invoice/
        [Authorize]
        public ActionResult InvoiceList()
        {
            var items = GetCurrentUserInvoices().Where(x => x.IdInvoiceState == 1).Select(x => new InvoiceModel(x)).ToList();
            return View(items);
        }

        //
        // POST: /Invoice/
        [HttpPost]
        [Authorize]
        public ActionResult InvoiceList(IEnumerable<InvoiceModel> model)
        {
            var report = PurchaseGoods();
            if (!report.HasError)
                return RedirectToAction("Index", "Home", null);
            else
                ModelState.AddModelError("", report.Message);
            return View(model);
        }

        [HttpPost]
        [Authorize]
        public JsonResult AddToCart(long idgood)
        {
            var user = GetUserByUsername(User.Identity.Name);
            var report = AddGoodToInvoice(idgood, user.Id);
            return Json(report.Message, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [Authorize]
        public JsonResult Delete(long id)
        {
            var user = GetUserByUsername(User.Identity.Name);
            var report = DeleteInvoiceById(id, user.Id);
            if (!report.HasError)
                return Json("Deleted", JsonRequestBehavior.AllowGet);
            else
                return Json(report.Message, JsonRequestBehavior.AllowGet);
        }
        
        [HttpGet]
        [Authorize]
        public JsonResult GetCartCount()
        {
            return Json(GetCurrentUserCartCount(), JsonRequestBehavior.AllowGet);
        }
	}
}

OnlineStoreMVC/OnlineStoreMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - دیجی رسا</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @if (IsSectionDefined("Style"))
    { 
        @RenderSection("Style");
    }
</head>
<body onload="UpdateCartCount();">
    <header class="header">
        <div class="mrg-auto defwidth">
            <div class="runit">
                <div class="topbar">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <table>
                            <tr>
                                <td>
                                    <div id="user-menu">
                                        <ul>
                                            <li>
                                                <a href="#" id="login">
                                                    <span class="arrow-icon" style="float:right;"></span>
                                                    <span class="user-icon" style="float:right;"></span>
                                                    <p id="loginLabel">@ViewData["FullName"] عزیز خوش آمدید</p>
                                                </a>
                                                <ul class="user-submenu">
                                                    @if (User.IsInRole("admin"))
                                                    {
                                                        <li>
                                                            @Html.ActionLink("پنل مدیریت", "AdminPanel", "Account", null, null)
                                                        </li>
                                                    }
                                                    <li>
                                                        @Html.ActionLink("ویرایش مشخصات", "Edit", "Account", null, null)
                                                    </li>
                                                    <li>
                                                        @Html.ActionLink("خروج", "Logout", "Account", null, null)
                                                    </li>
                                                </ul>
                                            </li>
                                        </ul>
                                    </div>
                                </td>
                            </tr>
                        </table>
                    }
                    else
                    {
                        <table>
                            <tr>
                                <td>
                                    <a href="#" id="login">
                                        <span class="login-icon" style="float:right;"></span>
                                        @Html.ActionLink("به حساب کاربری خود وارد شوید", "Login", "Account", new { @returnUrl = Request.RawUrl }, new { @id = "loginLabel" })
                                    </a>
                                </td>
                                <td style="width: 70%;">
                                    <div>
                                        <span class="user-icon" style="float:right;"></span>
                                        @Html.ActionLink("ثبت نام کنید", "Register", "Account", null, new { @id = "register" })
                                    </div>
                                </td>
                            </tr>
                        </table>
                    }
                </div>
                <div class="cart-box">
                    <a href="#" class="dk-button red" onclick="cartboxclick()">
                        <i class="dk-button-icon dk-button-icon-cart">
                        </i>
                        <div class="dk-button-label">
                            <div class="dk-button-labelname">سبد خرید</div>
                            <span class="order-count">0</span>
                        </div>
                    </a>
                </div>
                <div class="search-box">
                    <input type="text" id="SearchBox" placeholder="محصول مورد نظرتان را جستجو کنید ...">
                    <a id="btnSearch" href="@Url.Action("Index", "Good", null)" onclick="btnSearch_Click()"></a>
                </div>
            </div>
            <div class="logo-box">
                <a href="@Url.Action("Index", "Home", null)">
                    <img src="~/Images/logo-slogan.png" width="156" height="58" alt="فروشگاه اینترنتی ديجی راسا" title="ديجی راسا | بررسی، انتخاب و خرید آنلاین">
                </a>
            </div>
        </div>
        <script type="text/javascript">
            function btnSearch_Click() {
                debugger;
                var name = $('#SearchBox').val();
                var btn = $('#btnSearch');
                btn.attr('href', btn.attr('href') + '?searchstring=' + encodeURIComponent(name))
            };
            function pop(div) {
                $('#popDiv').show();
                $('#' + div).show();
            }
            function hide(div) {
                $('#popDiv').hide();
                $('#' + div).hide();
            }
            function load_cart() {
                $('#cart-table').load('@Url.Action("_PartialInvoiceList", "Invoice", null)');
            }
            function cartboxclick() {
                var auth = '@User.Identity.IsAuthenticated';
                if (auth == 'True') {
                    pop('popBuyList');
                    load_cart();
                } else {
                    alert("برای مشاهده ثبت خرید ابتدا ورود کنید");
                    window.location.href = '@Url.Action("Login", "Account", null)';
                }
            }
            function UpdateCartCount() {
                var auth = '@User.Identity.IsAuthenticated';
                if (auth == 'True') {
                    $.ajax({
                        url: '/Invoice/GetCartCount',
                        type: 'GET',
                        success: function (result) {
                            $('.order-count').html(result);
                        },
                        error: function () {
                            $('.order-count').hide();
                        }
                    });
                }
            }
        </script>
    </header>
    @Html.Action("_MainMenu", "Home")
    <div id="main">
        <section class="contents">
            @RenderBody()
        </section>
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - دیجی راسا</p>
        </footer>
    </div>
    <div id="popDiv" class="ontop" onclick="$('popDiv').hide();">
    </div>
    <div id="popBuyList" style="background:#000; display:none; width:700px; z-index: 20; position: absolute; top: 20%; left: 35%; margin-top: -50px; margin-left: -50px; direction:rtl;">
        <div id="inner2">
            <div id="header2">
                <div id="container2">
                    <a href="#" class="close" onclick="hide('popBuyList')"></a>
                    <div id="title2">سبد خرید</div>
                </div>
            </div>
            <div style="padding: 20px;">
                <input type="button" value="نهایی کردن خرید" onclick="location.href='@Url.Action("InvoiceList", "Invoice", null)'" class="btn btn-default" />
                <div id="cart-table">
                    @if (User.Identity.IsAuthenticated)
                    {
                        @Html.Action("_PartialInvoiceList", "Invoice", null)
                    }
                </div>
            </div>
        </div>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryval")
    @RenderSection("scripts", required: false)
</body>

</html>